# SITE SETUP

appearance:
  theme_day: minimal
  font: idaejin
  font_size: M

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: IE University
    description: 'Full time assistant professor'
    twitter: 'idaejin'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: ''
    license:
      enable: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/idaejin/idaejin.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
  search:
    provider: wowchemy
  map:
    provider: ''

extensions:
  academicons:
    enable: true

email: Dae-Jin.Lee@ie.edu
