enableInlineShortcodes = false
[exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^WC_POST_CSS']
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[funcs]
  getenv = ['^HUGO_', '^WC_POST_CSS']

[http]
  methods = ['(?i)GET|POST']
  urls = ['.*']