---
title: "Generalized Additive Models and beyond with P-splines"
subtitle: "XV Summer School MESIO, 2022" 
author: |
  | Dae-Jin Lee (dlee@bcamath.org)
  | BCAM - Basque Center for Applied Mathematics
date: "July 4-10, 2022"
output: 
  html_document: 
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---------------

### Requisites

  + Latest versión of `R` ([`https://www.r-project.org`](https://www.r-project.org)).

  + `Rstudio` is recommended ([`https://www.rstudio.com`](https://www.rstudio.com)).


### Libraries required

 ```{r, echo = TRUE, eval = FALSE}
install.packages(c("MASS","splines","nlme","SemiPar","mgcv","KernSmooth","gamlss","gamlss.dist","gamlss.add","ggplot2","lattice","latticeExtra"))
```

----------------

#  Slides

  - [Introduction](pdf/GAMS-and-beyond_0.pdf)
  - [Chapter 1](pdf/GAMS-and-beyond_1.pdf)
  - [Chapter 2](pdf/GAMS-and-beyond_2.pdf)
  - Soon
  - ...
  
# `R` code 

  - Real-time code sharing via [https://codeshare.io/6pMExg](https://codeshare.io/6pMExg)
